FROM jupyter/datascience-notebook
MAINTAINER "GGX"

RUN git clone https://github.com/cvignac/DiGress
RUN cd DiGress

RUN conda update -n base -y conda && conda install -n base -c conda-forge -y mamba #&&
RUN conda install -n base -c conda-forge graph-tool #&&
RUN mamba  install -y rdkit #&& 
RUN pip install pyyaml && pip install overrides imageio numpy scipy tqdm wandb hydra-core seaborn #&&
RUN pip install pytorch_lightning==1.6  torchmetrics torch==1.11 torchvision  --extra-index-url https://download.pytorch.org/whl/cu113 #&&
RUN pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.11.0+cu113.html
#RUN pip install pyyaml && pip install overrides imageio numpy scipy tqdm wandb hydra-core #&&
ADD src/analysis /workspace/analysis
ADD configs /workspace/configs
ADD src/diffusion /workspace/diffusion
ADD src/models /workspace/models
ADD ./data/qm9/qm9_pyg /workspace/data/qm9/qm9_pyg
ADD *.py /workspace/
RUN pip install -e .
# expects you to to run the image with `docker run -e WANDB_API_KEY=$YOUR_API_KEY graphgendiff:latest`
CMD python main.py




RUN pip install netrd==0.2.2
RUN conda install networkx=2.5 --force-reinstall -y
RUN conda install pandas=1.3 --force-reinstall -y
RUN conda install pytorch torchvision torchaudio -c pytorch -y
RUN git clone https://github.com/gerritgr/GINA
RUN cp GINA/GINA.ipynb GINA.ipynb
RUN rm -rf GINA/


# compile with (within the folder of Dockerfile):  docker build -t gerritgr/graphgenbaseline . (replace gerritgr with your username)
# start with: docker run -p 10000:8888 gerritgr/graphgenbaseline   # at my PC the default port doesn't work
