name: SPECTRE
channels:
  - pytorch
  - pyg 
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.9
  - pytorch=1.9.0
  - cudatoolkit
  - numpy=1.20.3
  - pytorch-lightning=1.4.9
  - networkx=2.6.3
  - pyyaml
  - matplotlib=3.4.2
  - jupyter
  - scipy
  - pyg
  - tensorboard
  - pyemd
  - graph-tool
  - pip:
    - torch-householder
    - pygsp
    - torch-ema
  - conda-forge::rdkit=2021.03.1
