name: SPECTRE
channels:
  - pytorch
  - pyg 
  - conda-forge
dependencies:
  - pip
  - python=3.9
  - cudatoolkit=11.1
  - pytorch=1.9
  - numpy=1.21
  - pytorch-lightning=1.5
  - networkx=2.6
  - pyyaml
  - matplotlib
  - jupyter
  - scipy
  - pyg=2.0
  - tensorboard=2.6
  - pyemd
  - graph-tool # Only available for linux/osx - needed to estimate SBM validity
  - rdkit
  - pip:
    - torch-householder
    - pygsp
    - torch-ema
