name: SPECTRE
channels:
  - pytorch
  - pyg 
  - conda-forge
dependencies:
  - python=3.0
  - pip
  - pytorch
  - mkl
  - cudatoolkit
  - numpy
  - pytorch-lightning
  - networkx=2.6
  - pyyaml
  - matplotlib
  - jupyter
  - scipy
  - pyg=2.0
  - tensorboard
  - pyemd
  - graph-tool # Only available for linux/osx - needed to estimate SBM validity
  - rdkit
  - pip:
    - torch-householder
    - pygsp
    - torch-ema
